language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - ./setup.py install
  - pip install -q coveralls
script:
  - coverage run --source=docktree,bin setup.py test
after_success:
  - coveralls
